theme: minima
title: WOW SO COOL
author: AidanGC
email: hapachew@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Just a test. 

# social links
twitter_username: Hapachew
github_username: Hapachew 

show_excerpts: true # set to false to remove excerpts on the homepage
